sailfishos/qtmozembed

src/qmozview_p.cpp, src/qmozview_p.h
**Moved from [gitlab](https://git.sailfishos.org/mer-core/qtmozembed/merge_requests/101).**
Present form autocomplete suggestions in the predictive text bar.
Currently only login form username suggestions are exposed as
autocomplete suggestions by the engine.
=> Show autocomplete suggestions in predictive text bar

src/qmozwindow.cpp, src/qmozwindow_p.cpp
…
This reverts commit 5482758178d33ca621c80146e5f89c8fef61d02a.
With https://github.com/sailfishos/gecko-dev/pull/44 applied a MozAfterPaint is being delivered after xulrunner has composited the web page and it can be displayed resulting in setReadyToPaint being called.
=> Revert Drop rendering guards until engine statuses are reported correctly. JB#55286 OMP#JOLLA-310

src/qmozwindow_p.cpp
DrawWindowOverlay no longer exists in nsBaseWidget [1]. CompositingFinished [2] is also called from the gecko compositor thread at the Render [3]. Hence, this will give us the same end result.
See also https://github.com/sailfishos/gecko-dev/pull/66
[1]
https://github.com/sailfishos/gecko-dev/blob/sailfishos-esr60/widget/nsBaseWidget.h#L453
[2]
https://github.com/sailfishos/gecko-dev/blob/sailfishos-esr78/embedding/embedlite/embedshared/nsWindow.cpp#L272
[3]
https://github.com/sailfishos-mirror/gecko-dev/blob/esr78/gfx/layers/composite/LayerManagerComposite.cpp#L1273
=> [qtmozembed] Emit drawOverlay from CompositingFinished. Fixes JB#55709 OMP#JOLLA-404

src/qmozgrabresult.cpp
If a the requested size is larger than the framework shrink it to fit
retaining the aspect ratio.
=> [qtmozembed] Fix corruption of requested oversized thumbnails. JB#55754 OMP#JOLLA-417

src/qmozextmaterialnode.cpp, src/quickmozview.cpp
Not ultimately the cause but use the dynamic toolbar height for the footer margin instead of resizing. 
And correct for any differences in the webview texture size and the item size so that if the item is resized but the texture isn't the view is still rendered at 1:1 proportions.
=> Fix apparent touch offset in a webview with a footer

src/qmozview_p.cpp, src/qmozview_p.h, src/qopenglwebpage.cpp, src/quickmozview.cpp
Reset is called upon goBack, goForward, reload, and load.
This PR contains 4 commits
1. Move goBack, goForward, stop, and reload to private class.
2. Change resetPainted as generic reset
3. Rename resetState to resetTouchState
4. Mark dynamic toolbar height dirty on reset
After this PR, dynamic toolbar is reset when going back and forth, load, and reload.
See also https://github.com/sailfishos/sailfish-browser/pull/941
=> Reset domContentLoaded during reset

src/qmozview_p.cpp, src/qmozview_p.h
The rootScrollFrame no longer exists in the EmbedLiteViewListener.
See also:
https://github.com/sailfishos/gecko-dev/pull/119
=> [qtmozembed] Drop rootScrollFrame argument. Fixes JB#56312 OMP#JOLLA-530

src/qmozview_p.cpp
Response was not initialised if "succeeded: false", default to an empty json.
=> [qtmozembed] Default to an empty json response in RecvSyncMessage. JB#56439 OMP#JOLLA-548

tests/components/tests/content/testHelper.js
There are multiple unit test cases failing but at least testHelper.js
loads now.
I was originally planning to add unit test case for contentWidth and contentHeight but as there are cases failing didn't want to do that in context of JB#56313 / OMP#JOLLA-531. Thus, just this small cleanup.
Added viewport related infos to https://github.com/sailfishos/sailfish-components-webview/pull/138
=> Cleanup unit tests a bit

src/qmozenginesettings.cpp, src/qmozenginesettings.h, src/qmozenginesettings_p.h
The preference type is used as a hint when passing preference value
towards the engine.
=> [qtmozembed] Add preference type to the setPreference. JB#56638 OMP#JOLLA-573

src/qmozenginesettings.cpp, src/qmozenginesettings.h
This way we do not break C++ usage of the setPreference.
=> [qtmozembed] Bring back previous setPreference and overload it. JB#56638 OMP#JOLLA-573

src/qmozview_p.cpp
QMozViewPrivate::touchEvent issues the commit when screen is tapped and that sent the extra keypress with xt9. I didn't notice any problems in the browser test pages with this and also https://webk.telegram.org works.
=> [qtmozembed] Fix text input with xt9. JB#56870

src/quickmozview.cpp
Emitting an orientationChange signal when the QuickMozView is added to a scene can cause a segmentation fault, because the QML engine isn't ready to be activated.
This change ensures the orientation is set correctly, but without emitting the signal.
=> [qtmozembed] Avoid sending orientation signal on scene changes. Fixes JB#57688

src/qmozview_p.cpp, src/qmozview_p.h
This fixes regression caused by commit sha1 b65152d7. Before that
change QtMozEmbed read primary screen's physicalDotsPerInch and set
that as a dpi of the EmbedLiteView. The set dpi is set for to the APZCTreeManager.
When going further down, the AsyncPanZoomController calculates touch start
tolerance back like StaticPrefs::apz_touch_start_tolerance() * GetDPI().
This apz_touch_start_tolerance is the static getter of apz.touch_start_tolerance preference.
Embedlite apz.touch_start_tolerance (0.0762785) ballpark matches
to the Android FF (0.06 - mobile.js). Meaning that formulate that is used in
sailfish-components-webview is good enough.
Signed-off-by: Raine Makelainen <raine.makelainen@jolla.com>
=> [qtmozembed] Use physicalDotsPerInch for EmbedLiteView dpi. Fixes JB#56899

src/qmozenginesettings.cpp, src/qmozenginesettings.h, src/qmozenginesettings_p.h
Adds a new "colorMode" property which can be used to set the "ui.systemUsesDarkTheme" property.
=> [qtmozembed] Add colorMode property for prefers-color-scheme support. JB#58394

rpm/qtmozembed-qt5.spec, src/EmbedQtKeyUtils.cpp, src/qmozcontext.cpp, src/qmozcontext.h, src/qmozcontext_p.h, src/qmozview_defined_wrapper.h, src/qmozview_p.cpp, src/qmozview_p.h, src/qmozviewcreator.h, src/qopenglwebpage.cpp, src/qopenglwebpage.h, src/quickmozview.cpp, src/quickmozview.h, tests/auto/desktop-qt5/searchengine/tst_searchengine.qml, tests/qmlmoztestrunner/testviewcreator.cpp, tests/qmlmoztestrunner/testviewcreator.h
Updates the spec file and makes minor chnages to support the updated ESR 91 gecko API.
This is an ESR 91 change, so currently in draft to prevent it being merged.
=> [qtmozembed] Changes needed to support ESR 91

src/qmozcontext.cpp, src/qmozopenglwebpage.cpp, src/qmozview_defined_wrapper.h, src/qmozview_p.cpp, src/qmozview_p.h, src/quickmozview.cpp, tests/auto/desktop-qt5/useragent/tst_useragent.qml
Main commit:
[qtmozembed] Don't skip pages without user interaction on goBack/Forward. JB#62664
The second parameter, added in ESR91, is aRequireUserInteraction.
Meaning that as true it skipped the pages that had no user interaction.
This broke a sailfish-browser unit tests for forward/backward navigation
and also made the back button act surprising in the Browser app when
it started jumping over pages in the history.
Some minor changes while at it.
=> Avoid skipping pages without user interaction on goBack/goForward

src/qmozviewcreator.h, tests/qmlmoztestrunner/main.cpp, tests/qmlmoztestrunner/testhelper.cpp, tests/qmlmoztestrunner/testhelper.h, tests/qmlmoztestrunner/testviewcreator.cpp, tests/test-definition/tests.xml
Main commit
[qtmozembed] Avoid running gecko shutdown on all the unit tests. JB#62626
There is now some problem on the shutdown sequence that makes
qmlmoztestrunner segfault, making all the unit tests fail
even if the main case it was intended to test succeeded.
So making the full shutdown now opt-in and having it tested in the
basicview case. Gets the problem still visible, but not confusing it
with tests for other functionality.
=> Skip full shutdown on every unit test

src/qmozopenglwebpage.cpp, src/qmozopenglwebpage.h, src/qmozview_p.cpp
No-op property here, just used for internal state keeping in sailfish-browser side. Can have it defined closer to where it's actually used, being simpler and easier to understand.
=> Remove virtual keyboard height and dead member variable

src/qmozview_p.cpp, src/qmozview_p.h
The code was assuming all displays are native portrait and thus on landscape displays the size tranposes got wrong, ending up with the resolution property reported wrong and then browser drawing the selection handles wrong.
Fixes also some variable name typos, uninitialized member variables and such.
=> Fix text selection landscape display positions
